### ISSUE TITLE
virtual unwind support for hard-float targets

### ISSUE THREAD

**Issue by japaric** [knurling-rs/probe-run#1]
general comment: the Thumb targets are backwards compatible. Both `thumbv7em-none-eabi` and `thumbv7em-none-eabihf` work fine on Cortex-M4F devices. If you are not doing floating point operations (`f32` math) then you can use the `thumbv7em-none-eabi` target, which is supported by `probe-run`, without any performance degradation.

---

The virtual unwinder doesn't expect floating pointer (FP) registers to be pushed on exception entry.

The Cortex-M is smart about this: it only pushes FP registers if the preempted context was using them.
The unwinder will need to compute at runtime whether the FP registers were pushed or not (there should be some flag/register pushed onto the stack that contains this info) and update the per-frame SP value accordingly while walking up the stack.

**Comment by mattico** [comment]
Is this the only (known) issue preventing hard-float ABI support?

**Comment by jonas-schievink** [comment]
I think so, yes

**Comment by japaric** [comment]
general comment: the Thumb targets are backwards compatible. Both `thumbv7em-none-eabi` and `thumbv7em-none-eabihf` work fine on Cortex-M4F devices. If you are not doing floating point operations (`f32` math) then you can use the `thumbv7em-none-eabi` target, which is supported by `probe-run`, without any performance degradation.

**Comment by mattico** [comment]
I am doing floating point operations on a Cortex-M7F. I'll look into fixing this when I try to integrate binfmt in the next month or so, if someone else doesn't fix it first.
