### ISSUE TITLE
Remove `--defmt` flag in favor of magic

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/probe-run#102]
The defmt RTT channel is named "defmt", so it can be automatically detected instead of having to pass `--defmt`.

**Comment by japaric** [comment]
Great idea! I would not remove the `--defmt` flag so we can ship this in the v0.1.x series; instead I would make it a NOP and maybe remove it from the CLI docs (`--help`)?

**Comment by jonas-schievink** [comment]
Yeah, sounds good
