### ISSUE TITLE
Probe-run is writing 0 to flash

### ISSUE THREAD

**Issue by David-OConnor** [knurling-rs/probe-run#137]
**Describe the bug**
Probe-run writes 0 to flash on STM32

**To Reproduce**
- Write to flash memory in the program (To a page beyond what the program itself takes up)
- Run (again) using probe run.

Expected: Flash memory value remain how they were on last explicit write
What happens: Flash memory is 0ed.

If I exit the probe-run terminal, then reset the MCU, flash memory writes and reads will work as normal, until you run with probe-run again, at which point the data will be wiped.

**Comment by jonas-schievink** [comment]
Does this also happen with cargo-flash? If so, this is likely to be a probe-rs bug.

**Comment by David-OConnor** [comment]
I don't know - I'll try to figure that out.

**Comment by Urhengulas** [comment]
Hi @David-OConnor, did you get to test if the error also occurs with `cargo-flash`?

**Comment by jonas-schievink** [comment]
This is very likely to be a probe-rs issue in the end, since we just call its download API to flash the chip, so closing.
