### ISSUE TITLE
add flag / env-var to select the probe by serial number

### ISSUE THREAD

**Issue by japaric** [knurling-rs/probe-run#14]
This is helpful when you want to `cargo-run` firmware on two or more different devices in parallel.

``` console
$ # terminal 1
$ cd path/to/firmware
$ PROBE_RUN_SN=abcdef012345 cargo run --bin radio-tx

$ # terminal 2
$ cd path/to/firmware
$ PROBE_RUN_SN=012345abcdef cargo run --bin radio-rx
```

In the above case the firmware can live in the same Cargo project.

When the firmware lives in different Cargo projects you can use the flag version.

``` console
$ # terminal 1
$ cd path/to/firmware-a
$ head .cargo/config
[target.thumbv7em-none-eabihf]
runner = "probe-run --serial-number abcdef012345 --chip nrf52"

$ cargo run --bin radio-tx

$ # terminal 2
$ cd path/to/firmware-b
$ head .cargo/config
[target.thumbv7em-none-eabihf]
runner = "probe-run --serial-number 012345abcdef --chip nrf52"

$ cargo run --bin radio-rx
```

**Comment by Lotterleben** [comment]
note from @jonas-schievink 
Before attaching to a chip, the probe needs to be opened. probe-rs gives us a way to query all connected probes (Probe::list_all), and we currently pick the first one. This is what needs to be changed.
