### ISSUE TITLE
probe-run does NOT quit when Ctrl-C pressed

### ISSUE THREAD

**Issue by novuscy** [knurling-rs/probe-run#156]
**Describe the bug**
When I launched a simple blinky program with infinite loop, probe-run v0.2.0 does NOT quit when Ctrl-C pressed，but if I switched back to v0.1.9, everything works fine.

Maybe something wrong with the signal-hook crate?

**Comment by fnafnio** [comment]
I am seeing this as well on Windows. As a workaround, in Powershell or Windows-CMD you can use Ctrl+Break to force-close probe-run

**Comment by novuscy** [comment]
> I am seeing this as well on Windows. As a workaround, in Powershell or Windows-CMD you can use Ctrl+Break to force-close probe-run

I'm using a Mac, perhaps the Ctrl-C of probe-run 0.2.0 does not work on macOS?
