### ISSUE TITLE
Add a way to see probe-rs logs.

### ISSUE THREAD

**Issue by Dirbaio** [knurling-rs/probe-run#169]
There's no way to see logs from probe-rs.

- `--verbose` doesn't work
- `RUST_LOG=trace` doesn't work.

This is a blocker in helping people coming to the probe-rs matrix channel asking for help with flashing issues etc. There's no way for them to provide the logs we need without patching and recompiling probe-run.

This is due to this check here https://github.com/knurling-rs/probe-run/blob/ca0b3c53e28bf607a9db03c01798778a17a967c8/src/main.rs#L117-L121

**Comment by Urhengulas** [comment]
Hi @Dirbaio, using #171 you should be able to get all logs by passing `-vv` to `probe-run`. Does this match your expactations?

**Comment by Dirbaio** [comment]
Yes! Works great, thank you! :)
