### ISSUE TITLE
Refactor: shorten & un-nest functions, re-think return values

### ISSUE THREAD

**Issue by Lotterleben** [knurling-rs/probe-run#180]
Opening this issue for visibility (and also because I'd like to do this :D)
Imo it'd help with readability and maintainability to do a refactoring run.

Things that I've been bumping into:
- [ ] checks in `notmain()` could be pulled into separate functions for readability 
- [x] `construct_backtrace()` is pretty long and involved; amount of parameters is smelly
- [x] `construct_backtrace()` always returns OK, even if there was an exception (then it's an `OK(Some(TopException))`). Returning a Result<(), TopException> would be more intuitive imo, but this could also be that I'm misunderstanding `anyhow::Error`
- [ ] `update_cfa()`has another unintuive return value, could be `Option<new_cfa>` imo

These can also be sneaked in as drive-bys on bugfixes and feature implementation.

**Comment by Urhengulas** [comment]
Totally agree that there is room for quite some refactoring!

Also we might want to add some unit, but also end-to-end tests. Maybe the kind of @jonas-schievink described in the github-actions blog Post :)

**Comment by Lotterleben** [comment]
very much agreed! I've tracked that one in https://github.com/knurling-rs/probe-run/issues/173 :D Maybe we can chat about planning/funds for this in the next bi-weekly?

**Comment by japaric** [comment]
`construct_backtrace` was refactored in PR #197

**Comment by Urhengulas** [comment]
@Lotterleben Do you consider this resolved by #222?

**Comment by Lotterleben** [comment]
very much so! thanks for the bump
