### ISSUE TITLE
"device halted without error" shouldn't be printed when using Ctrl+C

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/probe-run#231]
https://github.com/knurling-rs/probe-run/blob/563d92608b78eba211a3f333bb8135b3a3546b03/src/backtrace/mod.rs#L75

**Comment by Lotterleben** [comment]
Question while I'm working on this: Should a backtrace be printed by default after a user Ctrl+C's? From training experience, I'm leaning towards no (people think they've done something wrong when they see a backtrace). What do you think?

**Comment by jonas-schievink** [comment]
We've decided in https://github.com/knurling-rs/probe-run/issues/202 that it should print one

**Comment by Lotterleben** [comment]
got it, thx
