### ISSUE TITLE
Missing v0.2.4 release tag

### ISSUE THREAD

**Issue by newAM** [knurling-rs/probe-run#232]
I am unable to find a git tag for 0.2.4; would it be possible to get a tag for this version?  The git tags help out with packing; for example, with nixpkgs: https://github.com/NixOS/nixpkgs/blob/c079b35498711aa7e7995d18261e84c8bbc51cf0/pkgs/development/tools/rust/probe-run/default.nix

**Comment by Urhengulas** [comment]
I just tagged it. Cool to see `probe-run` being distributed in nixpkgs 😁
