### ISSUE TITLE
Add option to verify flash

### ISSUE THREAD

**Issue by MathiasKoch** [knurling-rs/probe-run#236]
It would be nice if you could add a cli option to verify the written flash, as this is now possible with probe-rs 0.11.0, but it default to false.

See https://github.com/probe-rs/probe-rs/pull/671/files for more details.

**Comment by Suyash458** [comment]
@Urhengulas I'd like to pick this one up! However, I don't have the hardware set up to verify it

**Comment by Urhengulas** [comment]
Hi @Suyash458, Thank you for your interest!

Do you have any microcontroller at hand? All of stm32, nordic, esp32 should work.
But even if not, I am able to test your PR.

**Comment by Suyash458** [comment]
@Urhengulas Thanks! I have an esp32 with me so I can test it out, I assume I don't need a JTAG debugger as well?

**Comment by Urhengulas** [comment]
@Suyash458 said:
> @Urhengulas Thanks! I have an esp32 with me so I can test it out, I assume I don't need a JTAG debugger as well?

You will need one a ST-Link, J-Link or CMSIS-DAP based probe, since that is what probe-rs supports. See https://probe.rs/docs/getting-started/probe-setup/.

In case you don't have one of those and can't get one I can test it out on real hardware for you.
