### ISSUE TITLE
Error: no probe was found

### ISSUE THREAD

**Issue by NathanMcMillan54** [knurling-rs/probe-run#238]
When I try to run anything with ``probe-run``, it shows an error that says ``Error: no probe was found``. I use the ``thumbv7em-none-eabi``, and I know the file path is right. What causes this and how can it be fixed? I use Ubuntu 20, and probe-run 0.2.3.

**Comment by NathanMcMillan54** [comment]
This sounds weird, I thought ``probe-run`` was for simulating boards like qemu. I didn't know you needed a real board. So oops.

**Comment by NathanMcMillan54** [comment]
I'll reopen this if anyone actually uses this right and has this issue.

**Comment by Urhengulas** [comment]
We will add this info to the error message and our troubleshooting section (#239). Therefore we can close it here I think 😄
