### ISSUE TITLE
Fix snapshot tests

### ISSUE THREAD

**Issue by BriocheBerlin** [knurling-rs/probe-run#279]
When running the snapshot tests, 3 of them fail, namely `panic_verbose`, `successful_run_can_enforce_backtrace` and `panic_is_reported_as_such`.

For one, setting up the canary takes a different amount of time.
Also name demangling seems to fail (see also  https://github.com/knurling-rs/probe-run/issues/201 )

<img width="481" alt="Screenshot 2021-11-18 at 13 19 52" src="https://user-images.githubusercontent.com/6567555/142632673-ec42e68a-4a2c-42ac-b58f-bc202c67b654.png">

Apparently the last good commit is `73ba0ccc90400c6dfd89005aab020917210fd5f6`, `Merge #253` . In between then and now there seem to be a changing number of failures.

**Comment by jonathanpallant** [comment]
https://github.com/knurling-rs/probe-run/pull/280 should fix the demangling?

**Comment by Lotterleben** [comment]
I've re-ran the tests on main– this issue seems to be fixed by now (by #280?), but one test still fails due to updated logging statements– will open a separate PR for that
