### ISSUE TITLE
Error with STM32F723IEKx

### ISSUE THREAD

**Issue by kalkyl** [knurling-rs/probe-run#29]
Here's what i get when i try using the provided "app-template" with the stm32f723 disco board via the onboard ST-LINK/V2-1

```
probe-run --chip STM32F723IEKx --defmt target/thumbv7em-none-eabihf/debug/hello`
flashing program ..
DONE
resetting device
Error: Error communicating with probe: A core architecture specific error occured

Caused by:
    0: A core architecture specific error occured
    1: Failed to read register DRW at address 0x0000000c because: An error specific to a probe type occured
    2: An error specific to a probe type occured
    3: Command failed with status SwdDpFault
```

**Comment by Yatekii** [comment]
I think this is really interesting to know! Because we see this error within cargo-embed/flash on some chips too. But atm I have no clue what causes it. So it seems like it's even different for two probe-rs users :/

**Comment by kalkyl** [comment]
See some progress after updating to latest:

```
probe-run --chip STM32F723IEKx target/thumbv7em-none-eabihf/debug/hello`
flashing program ..
DONE
resetting device
stack backtrace:
   0: 0x08000894 - __bkpt
   1: 0x08000864 - defmt_test::exit
   2: 0x0800045e - hello::__cortex_m_rt_main
   3: 0x08000408 - main
   4: 0x08000528 - ResetTrampoline
   5: 0x08000504 - Reset
Error: Error communicating with probe: A core architecture specific error occured

Caused by:
    0: A core architecture specific error occured
    1: Failed to read register DRW at address 0x0000000c because: An error specific to a probe type occured
    2: An error specific to a probe type occured
    3: Command failed with status SwdDpFault
```

**Comment by kalkyl** [comment]
It works with the Segger firmware on the ST-link for some reason...
https://www.segger.com/products/debug-probes/j-link/models/other-j-links/st-link-on-board/

**Comment by japaric** [comment]
> cargo embed works fine with the board FYI...

this could be because cargo-embed was using probe-rs 0.9 and probe-run was using probe-rs 0.8

@kalkyl we have just released probe-run 0.1.6 which uses probe-rs 0.10. Could you give that a try and see if the problem persists?

**Comment by kalkyl** [comment]
Hmm, still the same problem using the original st-link firmware....
And still works when i switch to the J-Link firmware

**Comment by kalkyl** [comment]
No IT WORKS, sorry i accidently reverted back to an old version of the st-link firmware (which would not work...)
So all good using version  `V2J37M26`!
Thanks, great job!
