### ISSUE TITLE
document `--json` in the book

### ISSUE THREAD

**Issue by japaric** [knurling-rs/probe-run#313]
#295 added the `--json` flag but it has not been documented in the book yet. It would be good to put it under the [printers section](https://defmt.ferrous-systems.com/printers.html)

**Comment by japaric** [comment]
and note that it can be used to change the format of the logs as asked in knurling-rs/defmt#664

**Comment by Dajamante** [comment]
`--json` flag documented in  https://github.com/knurling-rs/defmt/pull/669 (updated page `json output`)

**Comment by Dajamante** [comment]
Merged and closed.
