### ISSUE TITLE
v0.3.3 from crates.io does not install on current Debian Linux

### ISSUE THREAD

**Issue by BartMassey** [knurling-rs/probe-run#332]
Typing `cargo install probe-run` on current Debian Linux x86_64 fails during the link stage, apparently because it cannot find `libusb`; `libusb-1.0-0-dev` is correctly installed.

Installing from top-of-tree on the `probe-run` repo (commit bcaf997) via `cargo install --path .` works fine. Installing from the `v0.3.3` tag (commit 9226307) fails the same way as with installing from `crates.io`.

I have not bisected this, although I can if you have trouble reproducing. A failed build run is attached:
[`build-errors.txt`](https://github.com/knurling-rs/probe-run/files/9177114/build-errors.txt)

**Comment by Urhengulas** [comment]
Thank you for the report. This is a known issue with `rusb`. Please refer to https://github.com/knurling-rs/probe-run/issues/289 for details.

**Comment by BartMassey** [comment]
Apologies: looked at that issue before reporting, but didn't catch that it was the same. Thanks!

**Comment by Urhengulas** [comment]
No worries. It's the same root problem, but with different versions. As written in the other issue we still need a new release to fix it.
