### ISSUE TITLE
`actions-rs` is unmaintained

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/probe-run#338]
CI currently uses the `actions-rs/toolchain` action to install Rust, but the project is unmaintained: https://github.com/actions-rs/toolchain/issues/216

GHA comes with `rustup` preinstalled though, so we can just invoke that to install Rust instead.

**Comment by BriocheBerlin** [comment]
This seems to be already done. Should we close?

**Comment by jonas-schievink** [comment]
It's still used:

https://github.com/knurling-rs/probe-run/blob/8add0cf89438cb619e7ef7a26256805202eabe7e/.github/workflows/ci.yml#L46

**Comment by Urhengulas** [comment]
@BriocheBerlin said:
> This seems to be already done. Should we close?

So far I only updated it for `flip-link`, but there is nothing stopping us from implementing it in `probe-rs` and `defmt` as well.
