### ISSUE TITLE
Troubleshooting missing case where drivers are not installed

### ISSUE THREAD

**Issue by vadixidav** [knurling-rs/probe-run#356]
I tried the steps in troubleshooting and still got "Probe not found".

The solution turned out to be that this was a fresh computer and I had not installed ST software yet, so I was missing drivers for my ST-Link. I had to install `STSW-LINK009`.

A simple reminder in the troubleshooting for "Probe not found" to check to make sure your drivers are installed would resolve this.

**Comment by Urhengulas** [comment]
What operating system are you on?

**Comment by vadixidav** [comment]
Windows 11. It is already fixed. I just had to install the drivers for ST-Link. I opened this ticket to track adding driver installation to the readme.

**Comment by Urhengulas** [comment]
Yes, I just wanted to add on what operating system this could appear.
