### ISSUE TITLE
RP 2040: "ARM specific error"

### ISSUE THREAD

**Issue by JonasFocke01** [knurling-rs/probe-run#427]
Hello!  
Im a noob in embedded, so i could very well not be smart enough for this.  
I have a rpi pico and a rpi pico debug probe. I connected UART and SWD of the probe to the pico and flashed [this](https://github.com/majbthrd/DapperMime/releases) to the probe. It now gets recognized by `probe-run --list-probes` with `[0]: RP2040 CMSIS-DAP (VID: cafe, PID: 4005, Serial: 6E1614307E748BE2, CmsisDap)`, but running `probe-run --chip RP2040` results in `An ARM specific error`.  
This is the whole error message:
```bash
Error: An ARM specific error occurred.

Caused by:
    0: An error occurred in the communication with an access port or debug port.
    1: Target device did not respond to request.
```
What am i missing?

**Comment by BriocheBerlin** [comment]
Hey, your probe might be wired up wrong, or maybe the board isn't powered. A good place to ask such questions is the [rust-embedded matrix chat](https://matrix.to/#/#rust-embedded:matrix.org).
Also please note that we put probe-run into maintenance mode, see https://ferrous-systems.com/blog/probe-run-deprecation/ . Of course you can still use it, but you might want to switch to [probe-rs](https://probe.rs/).

**Comment by JonasFocke01** [comment]
Thank you for answering!
