### ISSUE TITLE
backtrace: Shorten paths to crates/libcore

### ISSUE THREAD

**Issue by jamesmunns** [knurling-rs/probe-run#66]
It would be nice to shorten long paths to rust libraries or published dependency crate versions, so your backtrace lines are better human-readable:

For core/alloc/std libraries, a format stating the version of the compiler used in a format similar to `rust-toolchain` file specifications would be good

`[stable-1.46.0]/lib/rustlib/src/foo.rs`

For published library dependencies, it would be good to use a similar format, with `$crate_name-$crate_version:

`[heapless-0.5.2]/src/vec.rs`

I think it would be reasonable to make this an option (perhaps the default?), as it may interfere with vscode's ability to jump to source. However, this would drastically reduce line lengths when that functionality is not needed.

**Comment by japaric** [comment]
> For core/alloc/std libraries, a format stating the version of the compiler used in a format similar to rust-toolchain file specifications would be good
>
> [stable-1.46.0]/lib/rustlib/src/foo.rs

(cross posting https://github.com/knurling-rs/probe-run/issues/65#issuecomment-842321239 here)

the contents file `$(rustc --print sysroot)/share/doc/rust/html/version_info.html` provided by the `rust-docs` component can be used to map the git hash in `/rustc/$HASH` paths to a Rust version.

But if we can get debuginfo remapping to work reliably (https://github.com/knurling-rs/probe-run/issues/65#issuecomment-842328184) then the channel name is path of the local path, e.g. `(..)/toolchains/stable-x86_64-unknown-linux-gnu`. The version appears to be present in rustup manifests within that folder

``` console
$ rg '1\.52\.1'
manifest-rustc-x86_64-unknown-linux-gnu
22:file:lib/libLLVM-12-rust-1.52.1-stable.so
(..)
```
