### ISSUE TITLE
Text not printed with rprint without newline 

### ISSUE THREAD

**Issue by jiayihu** [knurling-rs/probe-run#75]
I have a strange bug where `rprint!(".")` doesn't print anything until I print a newline `\n` later. For instance `rprint!(".\n");` works, `rprint!("."); rprint!("\n");` works too, and of course `rprintln!(".");` works. Characters are not missed, it's just as if some buffer is flushed only when newline is met.

This doesn't happen with cargo-embed so I created the issue here

**Comment by japaric** [comment]
Thanks for the report! Applications that print to the terminal will usually only flush after a newline. When `--defmt` is not used we should `flush` after each `write` to the `stdout`. So a `flush` after https://github.com/knurling-rs/probe-run/blob/df90d57c8e1e49b6a27df27a0769619ba032084e/src/main.rs#L430 should fix this issue.

**Comment by japaric** [comment]
@jiayihu could you try the latest (git) version of `probe-run` and let us know if this was fixed?

Re-opening until we heard back from the author

**Comment by jiayihu** [comment]
I'm currently stuck with other issues in the toolchain, I'll let you know ASAP!

**Comment by jiayihu** [comment]
Yeah works fine now and I think I'll stick with the git version, logs are prettier now 😄

**Comment by japaric** [comment]
Thanks for confirming!
