### ISSUE TITLE
Make qemu-run and probe-run share more code

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/probe-run#89]
probe-run implements a lot of ELF magic by itself, but it would be useful to pull that into this repo (presumably into elf2table) so that qemu-run can use and test it.

**Comment by Urhengulas** [comment]
Hi @jonas-schievink, What parts of the code are you referring to?

**Comment by jonas-schievink** [comment]
I think this is mostly done. It'd still be nice to base probe-run and qemu-run off of common functionality, but that doesn't seem terribly important right now.
